### ISSUE TITLE
Add support for providing custom labels

### ISSUE THREAD

**Issue by duartesaraiva98** [operatr-io/kpow-helm-charts#9]
For our deployment of Kpow we need to be able to provide custom labels. I would like to add this functionality to the chart. 

My proposal is to have a `labels` key in values, and the labels are added to both the `metadata.labels` and `spec.template.metadata.labels` in Deployment.

```
labels:
  label-one: value-one
```

**Comment by duartesaraiva98** [comment]
Pull Request #10 open for this issue

**Comment by d-t-w** [comment]
Thanks for raising this, and the associated PR, @duartesaraiva98.

We'll take a look at it shortly and get back to you.

**Comment by d-t-w** [comment]
Merged and closed thanks @duartesaraiva98 👍
